# Mapping commands to abbreviations
command_mapping = {
    #Headings
    "heading": "H",
    "head": "H",
    "Hheading": "H",
    "having": "H",
    "getting": "H",
    "adding": "H",

    #speeds
    "speed": "S",
    "speeds": "S",
    "reduce": "S",
    "increse": "S",
    "slow": "S",

    #altuides
    "maintain": "C",

    #locliser
    "intercept": "I",
    "locliser": "I",
    "inter": "I",
    "sept": "I",

    #directs
    "direct": "D",
    "derek": "D",
    "correct": "D",
    "directs": "D",

    #Phonetic alphabet
    "alpha": "A",
    "bravo": "B",
    "charlie": "C",
    "delta": "D",
    "echo": "E",
    "foxtrot": "F",
    "golf": "G",
    "gulf": "G",
    "hotel": "H",
    "india": "I",
    "juliet": "J",
    "julia": "J",
    "kilo": "K",
    "keeler": "K",
    "killer": "K",
    "lima": "L",
    "mike": "M",
    "november": "N",
    "oscar": "O",
    "papa": "P",
    "quebec": "Q",
    "qu bec": "Q",
    "romeo": "R",
    "sierra": "S",
    "tango": "T",
    "uniform": "U",
    "victor": "V",
    "whiskey": "W",
    "x-ray": "X",
    "x ray": "X",
    "yankee": "Y",
    "zulu": "Z",
    "hello": "Z",
}

# Mapping number words to their integer values
number_mapping = {
    "zero": "0",
    "era": "0",
    "one": "1",
    "two": "2",
    "tooth": "2",
    "to": "2",
    "three": "3",
    "four": "4",
    "for": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "ten": "10",
    "eleven": "11",
    "twelve": "12",
    "thirteen": "13",
    "fourteen": "14",
    "fifteen": "15",
    "sixteen": "16",
    "seventeen": "17",
    "eighteen": "18",
    "hundred": "00",
    "thousand": "000",
    "that": "000",
    "them": "000",
    "end": "000",
}
